# Generated by Django 4.1.5 on 2023-11-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='userId',
            new_name='userid',
        ),
    ]
